<?php

return PhpCsFixer\Config::create()
    ->setRules([
        '@PSR2' => true,
        'array_syntax' => ['syntax' => 'short'],
        'combine_consecutive_unsets' => true,
        'method_separation' => true,
        'no_multiline_whitespace_before_semicolons' => true,
        'single_quote' => true,
        'binary_operator_spaces' => [
            'align_double_arrow' => false,
            'align_equals' => false,
        ],
        'braces' => [
            'allow_single_line_closure' => true,
            'position_after_functions_and_oop_constructs' => 'same',
			'position_after_control_structures' => 'same',
        ],
        'cast_spaces' => true,
        'combine_consecutive_unsets' => true,
        'concat_space' => ['spacing' => 'one'],
        'declare_equal_normalize' => ['space' => 'single'],
        'elseif' => true,
        'encoding' => true,
        'function_typehint_space' => true,
        'hash_to_slash_comment' => true,
        'include' => true,
        'indentation_type' => true,
        'line_ending' => true,
        'lowercase_cast' => true,
        'lowercase_constants' => true,
        'method_argument_space' => ['keep_multiple_spaces_after_comma' => true],
        'method_separation' => true,
        'modernize_types_casting' => true,
        'new_with_braces' => false,
        'no_closing_tag' => true,
        'no_extra_consecutive_blank_lines' => [
            'curly_brace_block',
            'extra',
            'parenthesis_brace_block',
            'square_brace_block',
            'throw',
            'use',
        ],
        'no_leading_import_slash' => true,
        // 'no_leading_namespace_whitespace' => true,
        'no_mixed_echo_print' => ['use' => 'echo'],
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_multiline_whitespace_before_semicolons' => true,
        'no_php4_constructor' => true,
        'no_short_bool_cast' => false,
        'no_singleline_whitespace_before_semicolons' => true,
        'no_spaces_after_function_name' => true,
        'no_spaces_around_offset' => ['positions' => ['inside']],
        'no_spaces_inside_parenthesis' => false,
        'no_trailing_comma_in_list_call' => false,
        'no_trailing_comma_in_singleline_array' => false,
        'no_trailing_whitespace' => true,
        'no_trailing_whitespace_in_comment' => true,
        'no_unneeded_control_parentheses' => false,
        'no_unused_imports' => true,
        'no_useless_else' => true,
        'no_whitespace_before_comma_in_array' => true,
        'no_whitespace_in_blank_line' => true,
        'normalize_index_brace' => true,
        'not_operator_with_space' => true,
        'object_operator_without_whitespace' => true,
        'ordered_class_elements' => false,
        'ordered_imports' => true,
        'pow_to_exponentiation' => true,
        'pre_increment' => false,
        'protected_to_private' => false,
        'psr4' => true,
        'return_type_declaration' => ['space_before' => 'one'],
        'self_accessor' => true,
        'semicolon_after_instruction' => true,
        'short_scalar_cast' => true,
        'single_class_element_per_statement' => true,
        'single_import_per_statement' => true,
        'single_quote' => true,
        'switch_case_semicolon_to_colon' => true,
        'switch_case_space' => true,
        'ternary_operator_spaces' => true,
        'ternary_to_null_coalescing' => true,
        'trailing_comma_in_multiline_array' => true,
        'visibility_required' => true,
        'whitespace_after_comma_in_array' => true,

        // 'php_unit_construct' => false,
        // 'php_unit_dedicate_assert' => false,
        // 'php_unit_fqcn_annotation' => false,
        // 'php_unit_strict' => false,
        // 'php_doc_add_missing_param_annotation' => false,
        // 'phpdoc_align' => false,
        // 'phpdoc_annotation_without_dot' => false,
        // 'phpdoc_indent' => true,
        // 'phpdoc_inline_tag' => false,
        // 'phpdoc_no_access' => false,
        // 'phpdoc_no_alias_tag' => false,
        // 'phpdoc_no_empty_return' => false,
        // 'phpdoc_no_useless_inheritdoc' => false,
        // 'phpdoc_order' => true,
        // 'phpdoc_return_self_reference' => false,
        // 'phpdoc_scalar' => false,
        // 'phpdoc_separation' => true,


        // 'php_unit_fqcn_annotation' => true,
        // 'phpdoc_align' => true,
        // 'phpdoc_annotation_without_dot' => true,
        // 'phpdoc_indent' => true,
        // 'phpdoc_inline_tag' => true,
        // 'phpdoc_no_access' => true,
        // 'phpdoc_no_alias_tag' => true,
        // 'phpdoc_no_empty_return' => true,
        // 'phpdoc_no_package' => true,
        // 'phpdoc_no_useless_inheritdoc' => true,
        // 'phpdoc_return_self_reference' => true,
        // 'phpdoc_scalar' => true,
        // 'phpdoc_separation' => true,
        // 'phpdoc_single_line_var_spacing' => true,
        // 'phpdoc_summary' => true,
        // 'phpdoc_to_comment' => true,
        // 'phpdoc_trim' => true,
        // 'phpdoc_types' => true,
        // 'phpdoc_var_without_name' => true,
        // 'pre_increment' => true,
        // 'return_type_declaration' => true,
        // 'self_accessor' => true,
        // 'short_scalar_cast' => true,
        // 'single_blank_line_before_namespace' => true,
        // 'single_class_element_per_statement' => true,
        // 'space_after_semicolon' => true,
        // 'standardize_not_equals' => true,
        // 'ternary_operator_spaces' => true,
        // 'trailing_comma_in_multiline_array' => true,
        // 'trim_array_spaces' => true,
        // 'unary_operator_spaces' => true,
        // 'whitespace_after_comma_in_array' => true,
    ])
    ->setIndent("\t")
    ->setLineEnding("\n")
    ->setRiskyAllowed(true);
    // ->setUsingCache(false);
